Remove default URL length limit in Gunicorn
camptocamp/c2cgeoportal pull request #7881
Opened 2021-03-02 12:04 UTC by asaunier

We had several users reporting GMF crashes with long URLs (GMF has often permalink with a lot of params) such as:
```
Request Line is too large (5722 > 4094)
```

This is related to Gunicorn limiting by default URLs to 4094 chars: https://docs.gunicorn.org/en/stable/settings.html#limit-request-line

The PR suggests to get rid of the Gunicorn default limit.

2021-03-02 12:38 UTC, jwkaltz approved these changes

2021-03-02 14:00 UTC, arnaud-morvan approved these changes
LGTM.
Note that the gunicorn documentation says this limit is used to prevent DDOS attacks.

2021-03-03 06:23 UTC, jwkaltz commented
> this limit is used to prevent DDOS attacks.

Indeed, but since Gunicorn is normally not the front that is used

2021-03-04 11:08 UTC, sbrunner requested changes
Not sour that completely remove this limit is a good choice ...

2021-03-04 11:09 UTC, sbrunner commented
I prefer to set it to 8190...

2021-03-04 11:15 UTC, asaunier commented
@sbrunner OK, I have updated the PR accordingly.
@jwkaltz @arnaud-morvan Still OK for you?

2021-03-04 11:19 UTC, sbrunner approved these changes
Thanks :-)

2021-03-04 11:22 UTC, arnaud-morvan approved these changes

2021-03-04 11:53 UTC, jwkaltz approved these changes

2021-03-04 12:27 UTC, merged

2021-03-05 10:11 UTC, asaunier commented
Setting the limit to 8190 was the good choice here as the shorttener raises an exception if the URL > 8190 char anyway
https://github.com/camptocamp/c2cgeoportal/blob/master/geoportal/c2cgeoportal_geoportal/views/shortener.py#L81-L82