Add basic yamlutils script
camptocamp/c2cgeoportal pull request #9339
Opened 2022-02-22 14:10 UTC by danduk82

This PR adds a small script that flattens a yaml file. So for example:

```bash
cat << EOF > /tmp/file.yaml
---
a:
  aa:
    - 1
    - 2
  ab:
   - name: first
     value: firstvalue
   - name: second
     value: secondvalue
b:
  baa:
    merli:
      x: 1
      y:
        toto:
          bip:
            - 12
            - 24
        kiki: 42
  ba: 3
  df:
    xyz: 10
  bb: 4
EOF
```
gives the follow output when parsed by the script:
```bash
./yamlutils /tmp/file.yaml 
a.aa=1
a.aa=2
a.ab.name=first
a.ab.value=firstvalue
a.ab.name=second
a.ab.value=secondvalue
b.ba=3
b.bb=4
b.baa.merli.x=1
b.baa.merli.y.kiki=42
b.baa.merli.y.toto.bip=12
b.baa.merli.y.toto.bip=24
b.df.xyz=10
```

the script can be run in both a shell pipe or reading from a file
```bash
# as file
./yamlutils /tmp/file.yaml

# in a pipe
cat /tmp/file.yaml | ./yamlutils
```

2022-02-22 14:39 UTC, ger-benjamin approved these changes
Works well.
If there is no test, no doc to add, It's ready to merge for me

2022-02-28 10:01 UTC, sbrunner reviewed
This script looks to be really complicated, why using a Recursive Object instead of a recursive function?
For what do you need to flatten a YAML?

2022-02-28 13:05 UTC, danduk82 commented on bin/yamlutils
> +    )
I was thinking about adding a reverse version, from inline to yaml. But not implemented yet, and no time for it.

2022-02-28 13:06 UTC, danduk82 commented on bin/yamlutils
> +        yaml_content = YamlNode(yaml.load(document, Loader=yaml.FullLoader))
does safe loader work with yaml anchors and aliases?

2022-02-28 13:07 UTC, danduk82 commented on bin/yamlutils
> +    if other:
If you do so, you can use the script in a shell pipe, as the only argument that is not parsed by argparse it the input file. If you have a better way of doing please let me know

2022-02-28 13:08 UTC, danduk82 commented
@sbrunner , regarding the question "why a recursive object": because of lists of objects in yaml.

2022-02-28 13:11 UTC, danduk82 commented
also @sbrunner , I need to flatten Yaml because I find it a convenient way of debugging it. It's a very practical way of "grepping" and seeing what is set, at which level. Some errors of indendation might be more easy to read if you can just check the full path without the need of scrolling hunderds of lines of yaml

2022-03-01 10:56 UTC, sbrunner requested changes
not ready...

2022-03-01 11:17 UTC, sbrunner requested changes

2022-03-01 11:17 UTC, sbrunner commented on bin/yamlutils
> +    )
If it's not used it should be removed

2022-03-01 11:17 UTC, sbrunner commented on bin/yamlutils
> +    if other:
=> e.g.
```
import argparse
import sys


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('file', nargs='?', help='file to read')
    args = parser.parse_args()
    if args.file:
        print(args.file)
    else:
        print(sys.stdin.read())
```

2022-03-01 11:17 UTC, sbrunner commented on bin/yamlutils
> +        return out_str
Can be replaced by 
```python
def print_flat(data, path='', result=[]):
    if isinstance(data, dict):
        for key, value in data.items():
            print_flat(value, f'{path}.{key}' if path else key)
    elif isinstance(data, list):
        for value in data:
            print_flat(value, path)
    else:
        result.append(f'{path}={data}')
    return result
```

2022-03-01 12:25 UTC, danduk82 commented on bin/yamlutils
> +        return out_str
joli

2022-03-01 12:35 UTC, sbrunner approved these changes

2022-03-01 14:01 UTC, merged