Better documentation for LIDAR profile integration
camptocamp/c2cgeoportal pull request #9620
Opened 2022-04-27 10:00 UTC by llienher

Fix [GSGMF-1815](https://jira.camptocamp.com/browse/GSGMF-1815)

2022-04-27 13:31 UTC, llienher commented
@arnaud-morvan If you can see the CI error with jinja templating.

2022-04-30 09:03 UTC, arnaud-morvan commented
There are cookie cutter variables in this file, we cannot ignore cookie cutter templating on it, so I've added `{% raw %} {% endraw %} around the javascript code with `{{`.

2022-05-02 07:04 UTC, llienher commented
@arnaud-morvan Thanks for the fix !

2022-05-02 07:26 UTC, sbrunner requested changes
I stop my review because the changes speak about adding the LIDAR profile but he should ash about updating the LIDAR profile

2022-05-02 07:26 UTC, sbrunner commented on geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
> +4. For the LIDAR profile you should add/modify your controller constructor, in the interface JavaScript file:
The import is not in the constructor...

2022-05-02 07:26 UTC, sbrunner commented on geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
> +    +    this.ngeoToolActivateMgr.registerTool('mapTools', drawLidarprofilePanelActive, false);
This should be already present, then it's wrong...

2022-05-02 07:26 UTC, sbrunner commented on geoportal/c2cgeoportal_geoportal/scaffolds/update/{{cookiecutter.project}}/CONST_CHANGELOG.txt
> +    +  <body ng-class="{'gmf-profile-chart-active': !!profileChartActive, 'gmf-lidarprofile-chart-active': !!mainCtrl.lidarProfileFooterActive, 'gmf-query-grid-active': !!mainCtrl.queryGridActive}" n
This should be already present, then it's wrong...

2022-05-02 08:32 UTC, llienher commented
@sbrunner I made the doc shorter as it is of course updating, not add from nothing. :-)

2022-05-03 07:59 UTC, sbrunner approved these changes

2022-05-03 08:01 UTC, merged